# Usar una imagen oficial de Node.js
FROM node:18

# Establecer el directorio de trabajo
WORKDIR /app

# Copiar archivos necesarios
COPY package.json yarn.lock ./

# Instalar dependencias
RUN yarn install

# Copiar todo el código fuente
COPY . .

# Exponer el puerto de desarrollo
EXPOSE 3000

# Comando para iniciar el servidor de desarrollo
CMD ["yarn", "start"]
